= Board REST API Guide
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `PATCH`
| 기존 리소스의 일부를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `204 No Content`
| 기존 리소스를 성공적으로 수정함.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-errors]]
== 오류

[[resources]]
= 리소스

[[resources-index]]
== 인덱스

인덱스는 서비스 진입점을 제공한다.

=== 인덱스 조회

`GET` 요청을 사용하여 인덱스에 접근할 수 있다.

operation::index[snippets='response-body,http-response']

== 게시판

=== 게시판 목록 조회

`GET` 요청을 사용하여 모든 게시판을 조회할 수 있다.

operation::boards-list[snippets='response-fields,curl-request,http-request']

=== 게시판 조회

`GET` 요청을 사용하여 특정 게시판을 조회할 수 있다.

operation::boards-get-id[snippets='path-parameters,response-fields']
=== 게시판 생성

`POST` 요청을 사용해서 새 게시판을 등록할 수 있다.

operation::boards-create[snippets='request-fields,curl-request,http-request']

=== 게시판 수정

`PUT` 요청을 사용해서 게시판을 수정할 수 있다.

operation::boards-update[snippets='path-parameters,request-fields,curl-request,http-request']

=== 게시판 삭제

`DELETE` 요청을 사용해서 특정 게시판을 삭제할 수 있다.

operation::boards-delete[snippets='path-parameters,curl-request,http-request']

